/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as TrendingRouteImport } from './routes/trending'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RecentlyViewedRouteImport } from './routes/recently-viewed'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as NewArrivalsRouteImport } from './routes/new-arrivals'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HowWeReviewRouteImport } from './routes/how-we-review'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as EditorialPolicyRouteImport } from './routes/editorial-policy'
import { Route as DmcaRouteImport } from './routes/dmca'
import { Route as DealsRouteImport } from './routes/deals'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CollectionsRouteImport } from './routes/collections'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as BestProductsRouteImport } from './routes/best-products'
import { Route as BestOf2026RouteImport } from './routes/best-of-2026'
import { Route as AffiliateDisclosureRouteImport } from './routes/affiliate-disclosure'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReviewsIndexRouteImport } from './routes/reviews.index'
import { Route as GuidesIndexRouteImport } from './routes/guides.index'
import { Route as CompareIndexRouteImport } from './routes/compare.index'
import { Route as BrandsIndexRouteImport } from './routes/brands.index'
import { Route as ReviewsMacbookProRouteImport } from './routes/reviews.macbook-pro'
import { Route as ReviewsSlugRouteImport } from './routes/reviews.$slug'
import { Route as ProductsLaptopAirRouteImport } from './routes/products.laptop-air'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'
import { Route as GuidesSlugRouteImport } from './routes/guides.$slug'
import { Route as CompareSlugRouteImport } from './routes/compare.$slug'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as BrandSlugRouteImport } from './routes/brand.$slug'
import { Route as BestCategoryRouteImport } from './routes/best.$category'

const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const TrendingRoute = TrendingRouteImport.update({
  id: '/trending',
  path: '/trending',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RecentlyViewedRoute = RecentlyViewedRouteImport.update({
  id: '/recently-viewed',
  path: '/recently-viewed',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const NewArrivalsRoute = NewArrivalsRouteImport.update({
  id: '/new-arrivals',
  path: '/new-arrivals',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HowWeReviewRoute = HowWeReviewRouteImport.update({
  id: '/how-we-review',
  path: '/how-we-review',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorialPolicyRoute = EditorialPolicyRouteImport.update({
  id: '/editorial-policy',
  path: '/editorial-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const DmcaRoute = DmcaRouteImport.update({
  id: '/dmca',
  path: '/dmca',
  getParentRoute: () => rootRouteImport,
} as any)
const DealsRoute = DealsRouteImport.update({
  id: '/deals',
  path: '/deals',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsRoute = CollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const BestProductsRoute = BestProductsRouteImport.update({
  id: '/best-products',
  path: '/best-products',
  getParentRoute: () => rootRouteImport,
} as any)
const BestOf2026Route = BestOf2026RouteImport.update({
  id: '/best-of-2026',
  path: '/best-of-2026',
  getParentRoute: () => rootRouteImport,
} as any)
const AffiliateDisclosureRoute = AffiliateDisclosureRouteImport.update({
  id: '/affiliate-disclosure',
  path: '/affiliate-disclosure',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsIndexRoute = ReviewsIndexRouteImport.update({
  id: '/reviews/',
  path: '/reviews/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesIndexRoute = GuidesIndexRouteImport.update({
  id: '/guides/',
  path: '/guides/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareIndexRoute = CompareIndexRouteImport.update({
  id: '/compare/',
  path: '/compare/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsIndexRoute = BrandsIndexRouteImport.update({
  id: '/brands/',
  path: '/brands/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsMacbookProRoute = ReviewsMacbookProRouteImport.update({
  id: '/reviews/macbook-pro',
  path: '/reviews/macbook-pro',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsSlugRoute = ReviewsSlugRouteImport.update({
  id: '/reviews/$slug',
  path: '/reviews/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsLaptopAirRoute = ProductsLaptopAirRouteImport.update({
  id: '/products/laptop-air',
  path: '/products/laptop-air',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesSlugRoute = GuidesSlugRouteImport.update({
  id: '/guides/$slug',
  path: '/guides/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareSlugRoute = CompareSlugRouteImport.update({
  id: '/compare/$slug',
  path: '/compare/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandSlugRoute = BrandSlugRouteImport.update({
  id: '/brand/$slug',
  path: '/brand/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BestCategoryRoute = BestCategoryRouteImport.update({
  id: '/best/$category',
  path: '/best/$category',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/affiliate-disclosure': typeof AffiliateDisclosureRoute
  '/best-of-2026': typeof BestOf2026Route
  '/best-products': typeof BestProductsRoute
  '/categories': typeof CategoriesRoute
  '/collections': typeof CollectionsRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/deals': typeof DealsRoute
  '/dmca': typeof DmcaRoute
  '/editorial-policy': typeof EditorialPolicyRoute
  '/faq': typeof FaqRoute
  '/how-we-review': typeof HowWeReviewRoute
  '/login': typeof LoginRoute
  '/new-arrivals': typeof NewArrivalsRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/recently-viewed': typeof RecentlyViewedRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/trending': typeof TrendingRoute
  '/wishlist': typeof WishlistRoute
  '/best/$category': typeof BestCategoryRoute
  '/brand/$slug': typeof BrandSlugRoute
  '/category/$slug': typeof CategorySlugRoute
  '/compare/$slug': typeof CompareSlugRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/products/laptop-air': typeof ProductsLaptopAirRoute
  '/reviews/$slug': typeof ReviewsSlugRoute
  '/reviews/macbook-pro': typeof ReviewsMacbookProRoute
  '/brands/': typeof BrandsIndexRoute
  '/compare/': typeof CompareIndexRoute
  '/guides/': typeof GuidesIndexRoute
  '/reviews/': typeof ReviewsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/affiliate-disclosure': typeof AffiliateDisclosureRoute
  '/best-of-2026': typeof BestOf2026Route
  '/best-products': typeof BestProductsRoute
  '/categories': typeof CategoriesRoute
  '/collections': typeof CollectionsRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/deals': typeof DealsRoute
  '/dmca': typeof DmcaRoute
  '/editorial-policy': typeof EditorialPolicyRoute
  '/faq': typeof FaqRoute
  '/how-we-review': typeof HowWeReviewRoute
  '/login': typeof LoginRoute
  '/new-arrivals': typeof NewArrivalsRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/recently-viewed': typeof RecentlyViewedRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/trending': typeof TrendingRoute
  '/wishlist': typeof WishlistRoute
  '/best/$category': typeof BestCategoryRoute
  '/brand/$slug': typeof BrandSlugRoute
  '/category/$slug': typeof CategorySlugRoute
  '/compare/$slug': typeof CompareSlugRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/products/laptop-air': typeof ProductsLaptopAirRoute
  '/reviews/$slug': typeof ReviewsSlugRoute
  '/reviews/macbook-pro': typeof ReviewsMacbookProRoute
  '/brands': typeof BrandsIndexRoute
  '/compare': typeof CompareIndexRoute
  '/guides': typeof GuidesIndexRoute
  '/reviews': typeof ReviewsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/affiliate-disclosure': typeof AffiliateDisclosureRoute
  '/best-of-2026': typeof BestOf2026Route
  '/best-products': typeof BestProductsRoute
  '/categories': typeof CategoriesRoute
  '/collections': typeof CollectionsRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/deals': typeof DealsRoute
  '/dmca': typeof DmcaRoute
  '/editorial-policy': typeof EditorialPolicyRoute
  '/faq': typeof FaqRoute
  '/how-we-review': typeof HowWeReviewRoute
  '/login': typeof LoginRoute
  '/new-arrivals': typeof NewArrivalsRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/recently-viewed': typeof RecentlyViewedRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/trending': typeof TrendingRoute
  '/wishlist': typeof WishlistRoute
  '/best/$category': typeof BestCategoryRoute
  '/brand/$slug': typeof BrandSlugRoute
  '/category/$slug': typeof CategorySlugRoute
  '/compare/$slug': typeof CompareSlugRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/products/laptop-air': typeof ProductsLaptopAirRoute
  '/reviews/$slug': typeof ReviewsSlugRoute
  '/reviews/macbook-pro': typeof ReviewsMacbookProRoute
  '/brands/': typeof BrandsIndexRoute
  '/compare/': typeof CompareIndexRoute
  '/guides/': typeof GuidesIndexRoute
  '/reviews/': typeof ReviewsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/affiliate-disclosure'
    | '/best-of-2026'
    | '/best-products'
    | '/categories'
    | '/collections'
    | '/contact'
    | '/dashboard'
    | '/deals'
    | '/dmca'
    | '/editorial-policy'
    | '/faq'
    | '/how-we-review'
    | '/login'
    | '/new-arrivals'
    | '/privacy-policy'
    | '/recently-viewed'
    | '/search'
    | '/sitemap.xml'
    | '/terms'
    | '/trending'
    | '/wishlist'
    | '/best/$category'
    | '/brand/$slug'
    | '/category/$slug'
    | '/compare/$slug'
    | '/guides/$slug'
    | '/product/$slug'
    | '/products/laptop-air'
    | '/reviews/$slug'
    | '/reviews/macbook-pro'
    | '/brands/'
    | '/compare/'
    | '/guides/'
    | '/reviews/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/affiliate-disclosure'
    | '/best-of-2026'
    | '/best-products'
    | '/categories'
    | '/collections'
    | '/contact'
    | '/dashboard'
    | '/deals'
    | '/dmca'
    | '/editorial-policy'
    | '/faq'
    | '/how-we-review'
    | '/login'
    | '/new-arrivals'
    | '/privacy-policy'
    | '/recently-viewed'
    | '/search'
    | '/sitemap.xml'
    | '/terms'
    | '/trending'
    | '/wishlist'
    | '/best/$category'
    | '/brand/$slug'
    | '/category/$slug'
    | '/compare/$slug'
    | '/guides/$slug'
    | '/product/$slug'
    | '/products/laptop-air'
    | '/reviews/$slug'
    | '/reviews/macbook-pro'
    | '/brands'
    | '/compare'
    | '/guides'
    | '/reviews'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/affiliate-disclosure'
    | '/best-of-2026'
    | '/best-products'
    | '/categories'
    | '/collections'
    | '/contact'
    | '/dashboard'
    | '/deals'
    | '/dmca'
    | '/editorial-policy'
    | '/faq'
    | '/how-we-review'
    | '/login'
    | '/new-arrivals'
    | '/privacy-policy'
    | '/recently-viewed'
    | '/search'
    | '/sitemap.xml'
    | '/terms'
    | '/trending'
    | '/wishlist'
    | '/best/$category'
    | '/brand/$slug'
    | '/category/$slug'
    | '/compare/$slug'
    | '/guides/$slug'
    | '/product/$slug'
    | '/products/laptop-air'
    | '/reviews/$slug'
    | '/reviews/macbook-pro'
    | '/brands/'
    | '/compare/'
    | '/guides/'
    | '/reviews/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AffiliateDisclosureRoute: typeof AffiliateDisclosureRoute
  BestOf2026Route: typeof BestOf2026Route
  BestProductsRoute: typeof BestProductsRoute
  CategoriesRoute: typeof CategoriesRoute
  CollectionsRoute: typeof CollectionsRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  DealsRoute: typeof DealsRoute
  DmcaRoute: typeof DmcaRoute
  EditorialPolicyRoute: typeof EditorialPolicyRoute
  FaqRoute: typeof FaqRoute
  HowWeReviewRoute: typeof HowWeReviewRoute
  LoginRoute: typeof LoginRoute
  NewArrivalsRoute: typeof NewArrivalsRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  RecentlyViewedRoute: typeof RecentlyViewedRoute
  SearchRoute: typeof SearchRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  TrendingRoute: typeof TrendingRoute
  WishlistRoute: typeof WishlistRoute
  BestCategoryRoute: typeof BestCategoryRoute
  BrandSlugRoute: typeof BrandSlugRoute
  CategorySlugRoute: typeof CategorySlugRoute
  CompareSlugRoute: typeof CompareSlugRoute
  GuidesSlugRoute: typeof GuidesSlugRoute
  ProductSlugRoute: typeof ProductSlugRoute
  ProductsLaptopAirRoute: typeof ProductsLaptopAirRoute
  ReviewsSlugRoute: typeof ReviewsSlugRoute
  ReviewsMacbookProRoute: typeof ReviewsMacbookProRoute
  BrandsIndexRoute: typeof BrandsIndexRoute
  CompareIndexRoute: typeof CompareIndexRoute
  GuidesIndexRoute: typeof GuidesIndexRoute
  ReviewsIndexRoute: typeof ReviewsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trending': {
      id: '/trending'
      path: '/trending'
      fullPath: '/trending'
      preLoaderRoute: typeof TrendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recently-viewed': {
      id: '/recently-viewed'
      path: '/recently-viewed'
      fullPath: '/recently-viewed'
      preLoaderRoute: typeof RecentlyViewedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-arrivals': {
      id: '/new-arrivals'
      path: '/new-arrivals'
      fullPath: '/new-arrivals'
      preLoaderRoute: typeof NewArrivalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-we-review': {
      id: '/how-we-review'
      path: '/how-we-review'
      fullPath: '/how-we-review'
      preLoaderRoute: typeof HowWeReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editorial-policy': {
      id: '/editorial-policy'
      path: '/editorial-policy'
      fullPath: '/editorial-policy'
      preLoaderRoute: typeof EditorialPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dmca': {
      id: '/dmca'
      path: '/dmca'
      fullPath: '/dmca'
      preLoaderRoute: typeof DmcaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deals': {
      id: '/deals'
      path: '/deals'
      fullPath: '/deals'
      preLoaderRoute: typeof DealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections': {
      id: '/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof CollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/best-products': {
      id: '/best-products'
      path: '/best-products'
      fullPath: '/best-products'
      preLoaderRoute: typeof BestProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/best-of-2026': {
      id: '/best-of-2026'
      path: '/best-of-2026'
      fullPath: '/best-of-2026'
      preLoaderRoute: typeof BestOf2026RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/affiliate-disclosure': {
      id: '/affiliate-disclosure'
      path: '/affiliate-disclosure'
      fullPath: '/affiliate-disclosure'
      preLoaderRoute: typeof AffiliateDisclosureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews/': {
      id: '/reviews/'
      path: '/reviews'
      fullPath: '/reviews/'
      preLoaderRoute: typeof ReviewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/': {
      id: '/guides/'
      path: '/guides'
      fullPath: '/guides/'
      preLoaderRoute: typeof GuidesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/': {
      id: '/compare/'
      path: '/compare'
      fullPath: '/compare/'
      preLoaderRoute: typeof CompareIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands/': {
      id: '/brands/'
      path: '/brands'
      fullPath: '/brands/'
      preLoaderRoute: typeof BrandsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews/macbook-pro': {
      id: '/reviews/macbook-pro'
      path: '/reviews/macbook-pro'
      fullPath: '/reviews/macbook-pro'
      preLoaderRoute: typeof ReviewsMacbookProRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews/$slug': {
      id: '/reviews/$slug'
      path: '/reviews/$slug'
      fullPath: '/reviews/$slug'
      preLoaderRoute: typeof ReviewsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/laptop-air': {
      id: '/products/laptop-air'
      path: '/products/laptop-air'
      fullPath: '/products/laptop-air'
      preLoaderRoute: typeof ProductsLaptopAirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/$slug': {
      id: '/guides/$slug'
      path: '/guides/$slug'
      fullPath: '/guides/$slug'
      preLoaderRoute: typeof GuidesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/$slug': {
      id: '/compare/$slug'
      path: '/compare/$slug'
      fullPath: '/compare/$slug'
      preLoaderRoute: typeof CompareSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand/$slug': {
      id: '/brand/$slug'
      path: '/brand/$slug'
      fullPath: '/brand/$slug'
      preLoaderRoute: typeof BrandSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/best/$category': {
      id: '/best/$category'
      path: '/best/$category'
      fullPath: '/best/$category'
      preLoaderRoute: typeof BestCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AffiliateDisclosureRoute: AffiliateDisclosureRoute,
  BestOf2026Route: BestOf2026Route,
  BestProductsRoute: BestProductsRoute,
  CategoriesRoute: CategoriesRoute,
  CollectionsRoute: CollectionsRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  DealsRoute: DealsRoute,
  DmcaRoute: DmcaRoute,
  EditorialPolicyRoute: EditorialPolicyRoute,
  FaqRoute: FaqRoute,
  HowWeReviewRoute: HowWeReviewRoute,
  LoginRoute: LoginRoute,
  NewArrivalsRoute: NewArrivalsRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  RecentlyViewedRoute: RecentlyViewedRoute,
  SearchRoute: SearchRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  TrendingRoute: TrendingRoute,
  WishlistRoute: WishlistRoute,
  BestCategoryRoute: BestCategoryRoute,
  BrandSlugRoute: BrandSlugRoute,
  CategorySlugRoute: CategorySlugRoute,
  CompareSlugRoute: CompareSlugRoute,
  GuidesSlugRoute: GuidesSlugRoute,
  ProductSlugRoute: ProductSlugRoute,
  ProductsLaptopAirRoute: ProductsLaptopAirRoute,
  ReviewsSlugRoute: ReviewsSlugRoute,
  ReviewsMacbookProRoute: ReviewsMacbookProRoute,
  BrandsIndexRoute: BrandsIndexRoute,
  CompareIndexRoute: CompareIndexRoute,
  GuidesIndexRoute: GuidesIndexRoute,
  ReviewsIndexRoute: ReviewsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
